<a href="https://colab.research.google.com/github/CatarinaRRF/Churn_Alura_Voz/blob/main/notebooks/1-crf-initial-processamento-dos-dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <img style="display: inline; margin: 15px 0;" title="heartica_logo" src= https://raw.githubusercontent.com/CatarinaRRF/Churn_Alura_Voz/main/data/external/logo_alura_voz.png alt="" width="50" height="50"/><font color=2C3E50> **Ralatório de Análise I - Tratamento dos dados**</font>

![image.png]()

<font size="3.5">
<nav>
<a href='https://colab.research.google.com/drive/1pXJfmpMAZNaCfHaY-jMq-utUTGe3qHxl#scrollTo=6zK8HXbAiKIS'>Relatório II - Visualização de Dados</a> ||
<a href='https://colab.research.google.com/drive/1OEbCcqU4XS1l95fLunfQOuunN6vgx_xW#scrollTo=XfdinXNxd3wu'>Relatório III -Modelagem dos dados</a> ||
<a href='https://colab.research.google.com/drive/1dr5ARLZ5a0NRIaGm5Lr5mPavn4hyNwVj'>Relatório de Análise IV - Dashboard</a> ||
<a href='https://github.com/CatarinaRRF/Churn_Alura_Voz'>Github</a> ||
</nav>

# <font color=2C3E50> **01. Introdução**

<img style="display: inline; text-align:center; margin: 15px 0;" title="heartica_logo" src= https://camo.githubusercontent.com/aa692eada954179409fa3b8ab82fcac93f680effe075a086b1c523966e044f9e/68747470733a2f2f692e696d6775722e636f6d2f6a6e376b6d386f2e706e67 height="125"/>

A <font color=82D712>**Alura Voz**</font>, atua na área de telecomunicações através de serviços de telefônia e como Internet Service Provider (ISP), com diversas tecnologias de internet (DNS e Fibra Otica). No mercado desde 1999, a empresa atraiu diversos clientes e parceiros na área corporativa e de telefonia celular, e se firmou como forte nome nacional em soluções que integravam internet e internet móvel, apostando em sua capacidade de entrega de soluções altamente inovadora. Porém, recentemente vem apresentando uma <font color=82D712>*alta taxa de churn*</font> entre seus clientes, que tem prejudicado seu crescimento. <font color=82D712><strong>*</strong></font>
<br>
A **taxa de churn**, também conhecida como churn de clientes ou taxa de churn, é a taxa na qual os clientes param de fazer negócios com uma entidade. É mais frequentemente expresso como a porcentagem de assinantes do serviço que *pararam de assinar* durante um período de tempo específico. Para uma empresa expandir sua base de clientes, **sua taxa de crescimento** (medida pelo número de novos clientes) deve exceder **sua taxa de churn**. Desse modo, cabe ao cientista de dados responsavel, analizar as informações coletadas no banco de dados da empresa e destacar as informações necessarias, de modo, a auxiliar a tomada de deciçoes da empresa.<br>
Ao observar a <font color=82D712>**Base de dados da Alura Voz**</font>, verifica-se que é uma base disponibilizada via API em formato JSON com várias camandas de dados. Além disso acompanha um dicionario que contém o significados das informações das colunas do banco de dados, o dicionario é:<br>
</div>

|<font color=82D712>**Paramêtros: Cliente** ||<font color=82D712>**Descrição**|
|--------------------||--------------------------------|
|**customerID**      || Número de identificação único de cada cliente|
|**Churn**           || Se o cliente deixou ou não a empresa|
|**gender**          || Gênero (masculino e feminino)|
|**SeniorCitizen**   || Faixa etaria igual ou maior que 65 anos |
|**Partner**         || Se o cliente possui ou não um parceiro ou parceira|
|**Dependents**      || Se o cliente possui ou não dependentes|
|**tenure**          || Meses de contrato do cliente|

<br>

|<font color=82D712>**Paramêtros: Contrato** ||<font color=82D712>**Descrição**|
|------------------  ||--------------------------------|
|**Contract**        || Tipo de contrato|
|**PaperlessBilling**|| Se o cliente prefere receber online a fatura|
|**PaymentMethod**   || Forma de pagamento|
|**Charges.Monthly** || Total de todos os serviços do cliente por mês|
|**Charges.Total**   || Total gasto pelo cliente|

<br>

|<font color=82D712>**Paramêtros: Telefônia e Internet** ||<font color=82D712>**Descrição**|
|--------------------||--------------------------------|
|**PhoneService**    || Assinatura de serviço telefônico|
|**MultipleLines**   || Assisnatura de mais de uma linha de telefone|
|**InternetService** || Assinatura de um provedor internet|
|**OnlineSecurity**  || Assinatura adicional de segurança online|
|**OnlineBackup**    || Assinatura adicional de backup online|
|**DeviceProtection**|| Assinatura adicional de proteção no dispositivo|
|**TechSupport**     || Assinatura adicional de suporte técnico|
|**StreamingTV**     || Assinatura de TV a cabo|
|**StreamingMovies** || Assinatura de streaming de filmes|

<br>

---
<strong><font color=82D712>*</font> <font size="2">Disclamer:</strong> esta empresa é ficticia e esses dados não são reais

# <font color=2C3E50>**02. Impotação e Analise Inicial dos dados**

<font color=82D712> **Importando Bibliotecas**

In [ ]:
!pip install pandas-profiling==3.1.0

In [ ]:
import pandas as pd
import pandas_profiling
import numpy as np

<font color=82D712> **Analizando os Dados**

In [ ]:
API_Data = pd.read_json('/content/Telco-Customer-Churn.json')
API_Data.head(2)

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

As colunas do dataframe possuem dicionários como valores, logo, será utilizado o comando seguinte comando para este fim: <br>
> `<font color=82D712>pd.json_normalize</font>`

Esse código trasformará esses dicionários em novos dataframes, onde será então feito uma nova analize dos dados.

## <font color=2C3E50>**02.1. Analizando os Dados: <font color=82D712>Clientes**

In [ ]:
clientes = pd.json_normalize(data=API_Data['customer'])
clientes.head()

   gender  SeniorCitizen Partner Dependents  tenure
0  Female              0     Yes        Yes       9
1    Male              0      No         No       9
2    Male              0      No         No       4
3    Male              1     Yes         No      13
4  Female              1     Yes         No       3

In [ ]:
mapa_clientes = {'gender':'Sexo','SeniorCitizen':'Idoso',
                 'Partner':'Parceiros','Dependents':'Dependentes',
                 'tenure':'Tenure'}
                 
clientes = clientes.rename(columns = mapa_clientes)
clientes.head()

     Sexo  Idoso Parceiros Dependentes  Tenure
0  Female      0       Yes         Yes       9
1    Male      0        No          No       9
2    Male      0        No          No       4
3    Male      1       Yes          No      13
4  Female      1       Yes          No       3

<font color=82D712> **Analizando as variavéis únicas desse dataframe ...**

In [ ]:
for col in clientes:
   print("="*40)
   print('Valores Únicos da Coluna:', col)
   print('')
   print(clientes[col].unique())
   print('')

========================================
Valores Únicos da Coluna: Sexo

['Female' 'Male']

========================================
Valores Únicos da Coluna: Idoso

[0 1]

========================================
Valores Únicos da Coluna: Parceiros

['Yes' 'No']

========================================
Valores Únicos da Coluna: Dependentes

['Yes' 'No']

========================================
Valores Únicos da Coluna: Tenure

[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]



> Os <font color=82D712>**dados Binários**</font> (Yes/No)(Female/Male) podem gerar problemas em futuras analises, logo, trasformaremos em 0 e 1.

In [ ]:
correcao_clientes = ['Sexo', 'Parceiros', 'Dependentes',]

for column in correcao_clientes:
  clientes[column] = clientes[column].replace({"Male":0, "Female": 1, 'No':0, 'Yes':1})

In [ ]:
clientes.head()

   Sexo  Idoso  Parceiros  Dependentes  Tenure
0     1      0          1            1       9
1     0      0          0            0       9
2     0      0          0            0       4
3     0      1          1            0      13
4     1      1          1            0       3

## <font color=2C3E50>**02.2. Analizando os Dados: <font color=82D712>Telefone**

In [ ]:
telefone = pd.json_normalize(data=API_Data['phone'])
telefone.head()

  PhoneService MultipleLines
0          Yes            No
1          Yes           Yes
2          Yes            No
3          Yes            No
4          Yes            No

In [ ]:
mapa_telefone = {'PhoneService':'Telefonia',	'MultipleLines':'Multiplas_Linhas'}
                 
telefone = telefone.rename(columns = mapa_telefone)
telefone.head()

  Telefonia Multiplas_Linhas
0       Yes               No
1       Yes              Yes
2       Yes               No
3       Yes               No
4       Yes               No

<font color=82D712> **Analizando as variavéis únicas desse dataframe ...**

In [ ]:
for col in telefone:
   print("="*50)
   print('Valores Únicos da Coluna:', col)
   print('')
   print(telefone[col].unique())
   print('')

========================================
Valores Únicos da Coluna: Telefonia

['Yes' 'No']

========================================
Valores Únicos da Coluna: Multiplas_Linhas

['No' 'Yes' 'No phone service']

> Os <font color=82D712>**dados Binários**</font> (Yes/No) podem gerar problemas em futuras analises, logo, seram trasformadas em 0 e 1. Além disso, pode-se afirmar que os dados **'No phone service'** e **'No'** possuem mesma significado (no contexto dessa analise), então seram substituido tambem por 0.

In [ ]:
correcao_telefone = ['Telefonia',	'Multiplas_Linhas']

for column in correcao_telefone:
  telefone[column] = telefone[column].replace({'No':0, 'No phone service':0, 'Yes':1})

In [ ]:
telefone.head()

   Telefonia  Multiplas_Linhas
0          1                 0
1          1                 1
2          1                 0
3          1                 0
4          1                 0

## <font color=2C3E50>**02.3. Analizando os Dados: <font color=82D712>Internet**

In [ ]:
internet = pd.json_normalize(data=API_Data['internet'])
internet.head()

,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No

In [ ]:
mapa_internet = {'InternetService':'Internet',	'OnlineSecurity':'Segurança_On-line',	
                 'OnlineBackup': 'Backup_On-line',	'DeviceProtection':'Proteção_Dispositivos',	
                 'TechSupport':'Suporte_Técnico',	'StreamingTV':'TV_Streaming',	'StreamingMovies':'Streaming_Filmes'}
                 
internet = internet.rename(columns = mapa_internet)
internet.head()

,Internet,Segurança_On-line,Backup_On-line,Proteção_Dispositivos,Suporte_Técnico,TV_Streaming,Streaming_Filmes
0,DSL,No,Yes,No,Yes,Yes,No
1,DSL,No,No,No,No,No,Yes
2,Fiber optic,No,No,Yes,No,No,No
3,Fiber optic,No,Yes,Yes,No,Yes,Yes
4,Fiber optic,No,No,No,Yes,Yes,No

<font color=82D712> **Analizando as variavéis únicas desse dataframe ...**

In [ ]:
for col in internet:
   print("="*50)
   print('Valores Únicos da Coluna:', col)
   print('')
   print(internet[col].unique())
   print('')

============================================================
Valores Únicos da Coluna: Internet

['DSL' 'Fiber optic' 'No']

============================================================
Valores Únicos da Coluna: Segurança_On-line

['No' 'Yes' 'No internet service']

============================================================
Valores Únicos da Coluna: Backup_On-line

['Yes' 'No' 'No internet service']

============================================================
Valores Únicos da Coluna: Proteção_Dispositivos

['No' 'Yes' 'No internet service']

============================================================
Valores Únicos da Coluna: Suporte_Técnico

['Yes' 'No' 'No internet service']

============================================================
Valores Únicos da Coluna: TV_Streaming

['Yes' 'No' 'No internet service']

============================================================
Valores Únicos da Coluna: Streaming_Filmes

['No' 'Yes' 'No internet service']

> Os <font color=82D712>**dados Binários**</font> (Yes/No) podem gerar problemas em futuras analises, logo, seram trasformadas em 0 e 1. Além disso, pode-se afirmar que os dados 'No internet service' e 'No' possuem mesma significado (no contexto dessa analise), então seram substituido tambem por 0 (no)

In [ ]:
correcao_internet = ['Segurança_On-line',	'Backup_On-line',	'Proteção_Dispositivos',	
                     'Suporte_Técnico',	'TV_Streaming',	'Streaming_Filmes']

for column in correcao_internet:
  internet[column] = internet[column].replace({'No':0, 'No internet service':0, 'Yes':1})

In [ ]:
internet.head()

,Internet,Segurança_On-line,Backup_On-line,Proteção_Dispositivos,Suporte_Técnico,TV_Streaming,Streaming_Filmes
0,DSL,0,1,0,1,1,0
1,DSL,0,0,0,0,0,1
2,Fiber optic,0,0,1,0,0,0
3,Fiber optic,0,1,1,0,1,1
4,Fiber optic,0,0,0,1,1,0

> Os dados que possuem mais de duas variáveis, também podem gerar problemas em futuras análises, mas, não podem ser trasformadas em 0 e 1 . Desse modo, será usado o metodo de <font color=82D712>**One-Hot-Enconding**</font>, que fará cada variável uma nova coluna do tipo booleano(0 ou 1)

In [ ]:
internet = pd.get_dummies(data=internet, columns=['Internet'])
internet.head()

,Segurança_On-line,Backup_On-line,Proteção_Dispositivos,Suporte_Técnico,TV_Streaming,Streaming_Filmes,Internet_DSL,Internet_Fiber optic,Internet_No
0,0,1,0,1,1,0,1,0,0
1,0,0,0,0,0,1,1,0,0
2,0,0,1,0,0,0,0,1,0
3,0,1,1,0,1,1,0,1,0
4,0,0,0,1,1,0,0,1,0

In [ ]:
correcao_internet_2 = {'Internet_No':'Sem_internet'}

internet = internet.rename(columns = correcao_internet_2)
internet.head()

,Segurança_On-line,Backup_On-line,Proteção_Dispositivos,Suporte_Técnico,TV_Streaming,Streaming_Filmes,Internet_DSL,Internet_Fiber optic,Sem_internet
0,0,1,0,1,1,0,1,0,0
1,0,0,0,0,0,1,1,0,0
2,0,0,1,0,0,0,0,1,0
3,0,1,1,0,1,1,0,1,0
4,0,0,0,1,1,0,0,1,0

## <font color=2C3E50>**02.4. Analizando os Dados: <font color=82D712>Conta**

In [ ]:
conta = pd.json_normalize(data=API_Data['account'])
conta.head()

,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,One year,Yes,Mailed check,65.6,593.3
1,Month-to-month,No,Mailed check,59.9,542.4
2,Month-to-month,Yes,Electronic check,73.9,280.85
3,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Month-to-month,Yes,Mailed check,83.9,267.4

In [ ]:
mapa_conta = {'Contract':'Contrato',	'PaperlessBilling':'Pagamento_Eletrônico', 'PaymentMethod':'Método_Pagamento',
              'Charges.Monthly':'Cobrança_Mensal', 'Charges.Total':'Cobrança_Total'}
                 
conta = conta.rename(columns = mapa_conta)
conta.head()

,Contrato,Pagamento_Eletrônico,Método_Pagamento,Cobrança_Mensal,Cobrança_Total
0,One year,Yes,Mailed check,65.6,593.3
1,Month-to-month,No,Mailed check,59.9,542.4
2,Month-to-month,Yes,Electronic check,73.9,280.85
3,Month-to-month,Yes,Electronic check,98.0,1237.85
4,Month-to-month,Yes,Mailed check,83.9,267.4

<font color=82D712> **Analizando as variavéis únicas desse dataframe ...**

In [ ]:
for col in conta:
   print("="*60)
   print('Valores Únicos da Coluna:', col)
   print('')
   print(conta[col].unique())
   print('')

============================================================
Valores Únicos da Coluna: Contrato

['One year' 'Month-to-month' 'Two year']

============================================================
Valores Únicos da Coluna: Pagamento_Eletrônico

['Yes' 'No']

============================================================
Valores Únicos da Coluna: Método_Pagamento

['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

============================================================
Valores Únicos da Coluna: Cobrança_Mensal

[65.6  59.9  73.9  ... 91.75 68.8  67.85]

============================================================
Valores Únicos da Coluna: Cobrança_Total

['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

> Os <font color=82D712>**dados Binários**</font> (Yes/No) podem gerar problemas em futuras analises, logo, seram trasformadas em 0 e 1. Além disso, pode-se afirmar que os dados 'No internet service' e 'No' possuem mesma significado (no contexto dessa analise), então seram substituido tambem por 0 (no)

In [ ]:
correcao_conta = ['Pagamento_Eletrônico']

for column in correcao_conta:
  conta[column] = conta[column].replace({'No':0, 'Yes':1})

In [ ]:
conta.head()

,Contrato,Pagamento_Eletrônico,Método_Pagamento,Cobrança_Mensal,Cobrança_Total
0,One year,1,Mailed check,65.6,593.3
1,Month-to-month,0,Mailed check,59.9,542.4
2,Month-to-month,1,Electronic check,73.9,280.85
3,Month-to-month,1,Electronic check,98.0,1237.85
4,Month-to-month,1,Mailed check,83.9,267.4

> Os dados que possuem mais de duas variáveis, também podem gerar problemas em futuras análises, mas, não podem ser trasformadas em 0 e 1 . Desse modo, será usado o metodo de <font color=82D712>**One-Hot-Enconding**</font>, que fará cada variável uma nova coluna do tipo booleano(0 ou 1).

In [ ]:
conta = pd.get_dummies(data=conta, columns=['Contrato', 'Método_Pagamento'])
conta.head()

,Pagamento_Eletrônico,Cobrança_Mensal,Cobrança_Total,Contrato_Month-to-month,Contrato_One year,Contrato_Two year,Método_Pagamento_Bank transfer (automatic),Método_Pagamento_Credit card (automatic),Método_Pagamento_Electronic check,Método_Pagamento_Mailed check
0,1,65.6,593.3,0,1,0,0,0,0,1
1,0,59.9,542.4,1,0,0,0,0,0,1
2,1,73.9,280.85,1,0,0,0,0,1,0
3,1,98.0,1237.85,1,0,0,0,0,1,0
4,1,83.9,267.4,1,0,0,0,0,0,1

In [ ]:
correcao_conta_2 = {'Contrato_Month-to-month':'Contrato_Mensal', 'Contrato_One year':'Contrato_Anual', 'Contrato_Two year':'Contrato_Bianual',
                    'Método_Pagamento_Bank transfer (automatic)':'Pagamento_Transferência(Auto)',	
                    'Método_Pagamento_Credit card (automatic)':'Pagamento_Cartão_Crédito(Auto)',	
                    'Método_Pagamento_Electronic check':'Pagamento_Cheque_Eletronico',	
                    'Método_Pagamento_Mailed check':'Pagamento_Cheque_Email'}

conta = conta.rename(columns = correcao_conta_2)
conta.head()

,Pagamento_Eletrônico,Cobrança_Mensal,Cobrança_Total,Contrato_Mensal,Contrato_Anual,Contrato_Bianual,Pagamento_Transferência(Auto),Pagamento_Cartão_Crédito(Auto),Pagamento_Cheque_Eletronico,Pagamento_Cheque_Email
0,1,65.6,593.3,0,1,0,0,0,0,1
1,0,59.9,542.4,1,0,0,0,0,0,1
2,1,73.9,280.85,1,0,0,0,0,1,0
3,1,98.0,1237.85,1,0,0,0,0,1,0
4,1,83.9,267.4,1,0,0,0,0,0,1

<font color=82D712>**Criando uma coluna de Gastos diários**

In [ ]:
conta.insert(loc=1, column = 'Cobrança_Diário',  value = round(conta['Cobrança_Mensal']/30.5, 2))
conta.head ()

,Pagamento_Eletrônico,Cobrança_Diário,Cobrança_Mensal,Cobrança_Total,Contrato_Mensal,Contrato_Anual,Contrato_Bianual,Pagamento_Transferência(Auto),Pagamento_Cartão_Crédito(Auto),Pagamento_Cheque_Eletronico,Pagamento_Cheque_Email
0,1,2.15,65.6,593.3,0,1,0,0,0,0,1
1,0,1.96,59.9,542.4,1,0,0,0,0,0,1
2,1,2.42,73.9,280.85,1,0,0,0,0,1,0
3,1,3.21,98.0,1237.85,1,0,0,0,0,1,0
4,1,2.75,83.9,267.4,1,0,0,0,0,0,1

## <font color=2C3E50>**02.5. Analizando os Dados: <font color=82D712> Churn**

> Os <font color=82D712>**dados Binários**</font> (Yes/No) podem gerar problemas em futuras analises, logo, seram trasformadas em 0 e 1.

In [ ]:
API_Data['Churn'] = API_Data['Churn'].replace({'No':0, 'Yes':1})

In [ ]:
API_Data['Churn'].unique()

array([0, 1, ''], dtype=object)

# <font color=2C3E50>**03. Inconsistências**

<font color=82D712> **Concatenado os DataFrames e Visualizando suas Caractrísticas**

In [ ]:
df = pd.concat([API_Data['Churn'], clientes, telefone, internet, conta], axis=1)
df.head()

,Churn,Sexo,Idoso,Parceiros,Dependentes,Tenure,Telefonia,Multiplas_Linhas,Segurança_On-line,Backup_On-line,...,Cobrança_Diário,Cobrança_Mensal,Cobrança_Total,Contrato_Mensal,Contrato_Anual,Contrato_Bianual,Pagamento_Transferência(Auto),Pagamento_Cartão_Crédito(Auto),Pagamento_Cheque_Eletronico,Pagamento_Cheque_Email
0,0,1,0,1,1,9,1,0,0,1,...,2.15,65.6,593.3,0,1,0,0,0,0,1
1,0,0,0,0,0,9,1,1,0,0,...,1.96,59.9,542.4,1,0,0,0,0,0,1
2,1,0,0,0,0,4,1,0,0,0,...,2.42,73.9,280.85,1,0,0,0,0,1,0
3,1,0,1,1,0,13,1,0,0,1,...,3.21,98.0,1237.85,1,0,0,0,0,1,0
4,1,1,1,1,0,3,1,0,0,0,...,2.75,83.9,267.4,1,0,0,0,0,0,1

In [ ]:
report = pandas_profiling.ProfileReport(df, title="Relatorio dos Dados - Alura Voz", dark_mode=True)
report.to_file("Relatorio_inicial_ALURAVOZ.html")
report

---
<font color=82D712 size="5">**Conclusões**</font>

A partir da analise do report encontramos as seguintes inconsistencias:


*   <font color=82D712>**Churn**</font> tem números vazios 
*   <font color=82D712>**Tenure**</font> = 0 parece ser um dado estranho
*   <font color=82D712>**Cobrança total**</font> é do tipo object e deveria ser int

---
<font size="2">Para baixar e visualizar o html do relatorio em uma nova janela acesse a <font color=82D712><b>aba arquivos</b></font> do colab

## <font color=2C3E50>**03.1. Corrigindo Inconsistência no : <font color=82D712>Churn**

> O data set busca analisar o <font color=82D712>**Churn**</font>, mas, de acordo com o Pandas_Profile existem 224 faltantes o que representa 3.1% dos dados, esses linhas por não possuirem os valores target não são uteis para este relatório, logo, serão descartadas.

In [ ]:
df.drop(df.query("Churn == ''").index, inplace = True, axis = 0)
df.reset_index(drop=True, inplace=True)

In [ ]:
df['Churn'].dtype

dtype('O')

In [ ]:
df.Churn.unique()

array([0, 1], dtype=object)

In [ ]:
df['Churn'] = df['Churn'].astype(int)
df['Churn'].dtype

dtype('int64')

## <font color=2C3E50>**03.2. Corrigindo inconsistência no : <font color=82D712>Tenure**

Quando se analizou as var com o pandas_profile foi identificado que o valor minimo da variável <font color=82D712>**tenure**</font> é 0. Porém, para este tipo de dado (tempo de contrato) é estranho um cliente já que representa:

> ___"O número de meses que um Devedor teve uma conta com base na data de estabelecimento de conta ativa mais antiga para tal Devedor"___ <sup>[[1]](https://www.lawinsider.com/dictionary/customer-tenure).

Então, será necessário entender melhor esse parâmetro para determinar o que este dado representa e se é uma inconsistência. <br>
Também é identificado no relatório que o **<font color=82D712>tenure</font>** é altamente relacionado com o tipo de contrato, em especial, o ***mensal*** e o ***bianual***, então vamos analizar os dados 0 considerando esses cenários.

In [ ]:
tenure = pd.DataFrame(data=df, columns=['Tenure', 'Cobrança_Mensal', 'Cobrança_Total', 
                                        'Contrato_Mensal', 'Contrato_Anual', 'Contrato_Bianual'])

In [ ]:
tenure.query('Tenure == 0')

,Tenure,Cobrança_Mensal,Cobrança_Total,Contrato_Mensal,Contrato_Anual,Contrato_Bianual
945,0,56.05,,0,0,1
1731,0,20.00,,0,0,1
1906,0,61.90,,0,0,1
2025,0,19.70,,0,1,0
2176,0,20.25,,0,0,1
2250,0,25.35,,0,0,1
2855,0,73.35,,0,0,1
3052,0,25.75,,0,0,1
3118,0,52.55,,0,0,1
4054,0,80.85,,0,0,1
5433,0,19.85,,0,0,1

In [ ]:
tenure.query('Contrato_Bianual == 1').shape[0]

1695

In [ ]:
tenure.query('Contrato_Bianual == 1').query('Tenure == 48').head()

,Tenure,Cobrança_Mensal,Cobrança_Total,Contrato_Mensal,Contrato_Anual,Contrato_Bianual
151,48,79.65,3870.3,0,0,1
302,48,20.05,1036,0,0,1
768,48,39.40,1978.65,0,0,1
1258,48,20.65,1057,0,0,1
1520,48,19.55,883.35,0,0,1

---
<font color=82D712 size="5">**Conclusões**</font>

* Pode-se observar que todos que possuem tenure igual a 0 também possuem contrato do tipo Bianual/Anual, mas, que nem toda pessoa com esse tipo de contrato possui esse tenure, logo, não se pode afirmar que o tenure 0 é relacionado ao tipo de contrato. <br>
* Além disso, as linhas de tenure 0, tem suas cobranças totais vazias, mas, possum valores pagos nas cobranças mensais.

Logo, esses dados podem significar três coisas:
1. 0 representa ***o primeiro mês do contrato*** e a cobrança total tem valor 0, pois, ainda não foi cobrado a mensalidade.
2. A empresa pode ofertar um serviço de ***avaliação gratuita***, por isso no primeiro mês a cobrança é 0. 
3. Houve algum ***erro*** durante o armazenamento desses dados

De qualquer forma, não afetam de forma drastica a variável target e outras informações presentes nessas linhas podem ser uteis futuramente. Logo, seram mantidas dessa forma.

## <font color=2C3E50>**03.3. Corrigindo inconsistência na: <font color=82D712>Cobrança Total**

In [ ]:
df['Cobrança_Total'].dtype

dtype('O')

In [ ]:
df['Cobrança_Total'] = pd.to_numeric(df['Cobrança_Total'], errors='coerce')
df['Cobrança_Total'].dtype

dtype('float64')

In [ ]:
df.index

RangeIndex(start=0, stop=7043, step=1)

# <font color=2C3E50>**04. Export e Conclusões**

<font color=82D712>**Exports**

In [ ]:
report2 = pandas_profiling.ProfileReport(df, title="Relatorio dos Dados - Alura Voz", dark_mode=True)
report2.to_file("Relatorio_inicial_2_ALURAVOZ.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df.to_csv(r'data_alura_voz.csv', index = False)

<font color=82D712>**Conclusão**</font>

Será necessário fazer uma análise gráfica para entender quais as variáveis que são relacionadas com o churn para que a equipe de vendas tenha uma <font color=82D712>**noção do cenário atual**</font>, e também para que seja possivél entender de uma forma mais clara os dados e facilite a formação de possíveis hipóteses do que está acontecendo com os clientes.

Planeja-se então, fazer uma <font color=82D712>**análise estatística dos dados**</font>, verificar os tipos de dados que temos, gerar <font color=82D712>**gráficos de distribuição**</font> de dados binários ou categóricos, plot de Boxplots para detecção de outliers e matriz de correlação. Ou seja, uma Visualização dos dados.

---
<font color=82D712 size="2"><a href='https://colab.research.google.com/drive/1pXJfmpMAZNaCfHaY-jMq-utUTGe3qHxl#scrollTo=6zK8HXbAiKIS'> **Próximo ➜**</a></font>